### ISSUE TITLE
mount.nfs: operation not permitted

### ISSUE THREAD

**Issue by rabbagliettiandrea** [kubernetes-sigs/aws-fsx-openzfs-csi-driver#55]
/kind bug

**What happened?**
```
E0925 08:59:34.746298       1 mount_linux.go:232] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,timeo=60,soft fs-xxxxxxxx.fsx.eu-central-1.amazonaws.com:/fsx/pvc-4676b1ae-124c-4632-9f25-ae997e341416 /var/lib/kubelet/pods/2d3305e8-2c95-4987-83ab-0cc83c021a17/volumes/kubernetes.io~csi/pvc-4676b1ae-124c-4632-9f25-ae997e341416/mount
Output: mount.nfs: Operation not permitted
```

**What you expected to happen?**
CSI correctly mounting FSx Volume

**How to reproduce it (as minimally and precisely as possible)?**
Instantiate a PVC and set a POD to use it

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): EKS 1.27
- Driver version: 1.1.0

**Comment by gomesjason** [comment]
We believe your issue stems from from your environment opposed to the driver itself. Could you double check your network configuration? Ensure your filesystem's security group allows NFS inbound traffic, and that the filesystem lives under the same VPC as the EKS cluster.

If you are still encountering issues, could you let us know what type of filesystem you are creating? Are you making modifications to the NFS Exports parameter that may restrict mounting?

**Comment by rabbagliettiandrea** [comment]
Hi @gomesjason thank you for your kind response, I really appreciate it :)

> We believe your issue stems from from your environment opposed to the driver itself

I don't think so, look: I am currently using NFS CSI driver (https://github.com/kubernetes-csi/csi-driver-nfs) in order to access to the same FSx Filesystem of which I was using with _aws-fsx-openzfs-csi-driver_ and all works well

> Ensure your filesystem's security group allows NFS inbound traffic

Yes

>  that the filesystem lives under the same VPC as the EKS cluster

Yes

> If you are still encountering issues, could you let us know what type of filesystem you are creating? Are you making modifications to the NFS Exports parameter that may restrict mounting?

StorageClass type: Volume
Filesystem type: OpenZFS
NFS Exports parameter: rw,crossmnt

The thing is, the driver sees the PVC (in PENDING status) -> instantiate correctly the volume (in 90secs) -> than correctly set BOUND status on the PVC -> the POD remains in ContainerCreating status.. if I do describe in that POD kubelet tells me the above error.

If I query the driver node pod for logs I see the same error. Maybe is the fact that I am trying to mount it in a non-root container? I don't think so, but just to let you know..

Thank you so much for any suggestion, very welcome.

Keep it up with your wonderful work guys, kudos 👍🏻

**Comment by gomesjason** [comment]
I attempted to reproduce the issue with no luck. I was able to dynamically provision and mount a volume using kustomize, and our example manifests. I also tried using a pod running as a non-root user and was able to mount. Since you can mount using the the NFS driver it should be safe to assume your AWS environment is set up correctly.

> Maybe is the fact that I am trying to mount it in a non-root container?

What is the security context you are setting on the pod? Are you also changing the security context of the driver itself? Are you deploying with Helm, and if so, are you changing the configuration of any of the chart files?

Does this issue still occur when you create the driver using Kustomize, use version 1.0 of the driver, or dynamically provision a filesystem? That greatly helps us narrow down the root cause.

> Keep it up with your wonderful work guys, kudos 👍🏻

Thank you, we appreciate the kind words 😄

**Comment by rabbagliettiandrea** [comment]
Hello @gomesjason :)
I really believe that it will work with Kustomize and the issue is just on the helm chart side.
At the moment I don't have the opportunity to go with Kustomize though 👍🏻

**Comment by jacobwolfaws** [comment]
@rabbagliettiandrea If I understanding correctly, you're using dynamic provisioning to create a filesystem & try to mount it, but you're experiencing this error
```
Mounting arguments: -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,timeo=60,soft fs-xxxxxxxx.fsx.eu-central-1.amazonaws.com:/fsx/pvc-4676b1ae-124c-4632-9f25-ae997e341416 /var/lib/kubelet/pods/2d3305e8-2c95-4987-83ab-0cc83c021a17/volumes/kubernetes.io~csi/pvc-4676b1ae-124c-4632-9f25-ae997e341416/mount
Output: mount.nfs: Operation not permitted
```
When you use the nfs csi driver, you're creating a file system outside the nfs csi driver, then mounting it using the driver, correct?

Can you try using static provisioning with the openzfs csi driver to mount the same filesystem you're mounting with the nfs csi driver? This would be helpful in isolating the problem. Thanks!

**Comment by gomesjason** [comment]
/close

Closing issue as it has become inactive. Feel free to reopen if you still are experiencing issues.

**Comment by Jasper-Ben** [comment]
We are running into the same issue with dynamically provisioned volumes:

```
Mounting arguments: -t nfs -o nfsvers=4.1,wsize=1048576,rsize=1048576,timeo=600 fs-001c17b978cb65fe4.fsx.eu-central-1.amazonaws.com:/fsx/pvc-a87adf76-9347-414f-b3de-d41bf66d7238 /var/lib/kubelet/pods/a3c4534b-462c-45dc-9acc-caef4e5e21ea/volumes/kubernetes.io~csi/pvc-a87adf76-9347-414f-b3de-d41bf66d7238/mount
Output: mount.nfs: Operation not permitted
```


I am at a loss to what we might be doing wrong in our setup. To me it seems to align with the example setup from the driver documentation. Currently, I tend to think it is a problem with the driver.

Our setup is as follows...

csi-driver:
```hcl
# IAM
module "iam_role" {
  source       = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  version      = "~> 5.0"
  create_role  = true
  role_name    = "${local.release_name}-fsx-openzfs-access-${var.eks_cluster_name}"
  provider_url = var.eks_oidc_provider
  role_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonFSxFullAccess"
  ]

  oidc_fully_qualified_audiences = ["sts.amazonaws.com"]
  oidc_fully_qualified_subjects  = ["system:serviceaccount:${var.namespace}:${local.serviceaccount}"]
  tags = merge(
    var.common_tags,
    {
      "Name" = "${local.release_name}-fsx-openzfs-access-${var.eks_cluster_name}"
    },
  )
}


# the driver
resource "helm_release" "fsx_openzfs_csi_driver" {
  name      = var.release_name
  namespace = var.namespace
  repository = "https://kubernetes-sigs.github.io/aws-fsx-openzfs-csi-driver"
  chart      = "aws-fsx-openzfs-csi-driver"
  version    = "1.1.0"

  values = [
    file("${path.module}/helm_values.yaml"),
    yamlencode(var.extra_helm_configuration),
    yamlencode({
        customLabels = local.common_labels_k8s
        controller = {
            serviceAccount = {
                name = local.serviceaccount
                annotations = {
                    "eks.amazonaws.com/role-arn" = module.iam_role.iam_role_arn
                }
            }
        }
  })]
}
```

fsx-openzfs FS:
```hcl
module "k8s_coder_fsx_openzfs_fs" {
  source  = "terraform-aws-modules/fsx/aws//modules/openzfs"
  version = "1.0.1"

  name   = "coder-fsx-openzfs-fs"

  # File system
  automatic_backup_retention_days   = 90
  copy_tags_to_backups              = true
  copy_tags_to_volumes              = true
  daily_automatic_backup_start_time = "01:00"
  deployment_type                   = "MULTI_AZ_1"

  preferred_subnet_id = data.aws_subnets.vpc_private_subnets.ids[0]

  root_volume_configuration = {
    copy_tags_to_snapshots = true
    data_compression_type  = "LZ4"

    nfs_exports = {
      client_configurations = [
        {
          clients = "*"
          options = ["sync", "rw", "crossmnt"]
        }
      ]
    }
  }

  route_table_ids  = data.aws_route_tables.route_tables_private.ids
  storage_capacity = 1024
  subnet_ids = [
    data.aws_subnets.vpc_private_subnets.ids[0],
    data.aws_subnets.vpc_private_subnets.ids[1]
  ]
  throughput_capacity           = 160
  weekly_maintenance_start_time = "6:01:00"

  tags = local.common_tags
}
```

We also add the following security group to the node (output from the fsx terraform module):

Inbound rules:
![Screenshot from 2024-05-15 12-16-46](https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/assets/12223583/706df744-0056-4ff6-9857-4d9cdae274e5)

Outbound rules:
![Screenshot from 2024-05-15 12-16-57](https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver/assets/12223583/b29e8685-bc43-4515-a745-b2a67e3416b5)

Storageclass:

```hcl
resource "kubernetes_storage_class" "k8s_coder_fsx_openzfs" {
  metadata {
    name = "k8s-coder-fsx-openzfs-sc"
  }
  storage_provisioner = "fsx.openzfs.csi.aws.com"
  reclaim_policy      = "Delete"
  parameters = {
    ResourceType        = "volume"
    ParentVolumeId      = jsonencode(module.k8s_coder_fsx_openzfs_fs.file_system_root_volume_id)
    CopyTagsToSnapshots = "true"
    DataCompressionType = jsonencode("LZ4")
    OptionsOnDeletion   = jsonencode(["DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"])
    NfsExports = jsonencode([
      {
        "ClientConfigurations" : [
          {
            "Clients" : "*",
            "Options" : [
              "sync",
              "rw",
              "crossmnt"
            ]
          }
        ]
      }
    ])
    StorageCapacityReservationGiB = "-1"
    StorageCapacityQuotaGiB       = "-1"
    ReadOnly                      = "false"
    RecordSizeKiB                 = "128"
  }
  allow_volume_expansion = false
  mount_options = [
    "nfsvers=4.1",
    "rsize=1048576",
    "wsize=1048576",
    "timeo=600"
  ]
}
```

Test Storageclass & PVC according to docs example (unmodified except for root volume id) and PV consume:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.openzfs.csi.aws.com
parameters:
  ResourceType: "volume" #REQUIRED
  ParentVolumeId: '"fsvol-01d8f105375eac06b"' #REQUIRED
  CopyTagsToSnapshots: 'false'
  DataCompressionType: '"NONE"'
  NfsExports: '[{"ClientConfigurations": [{"Clients": "*", "Options": ["rw","crossmnt"]}]}]'
  ReadOnly: 'false'
  RecordSizeKiB: '128'
  StorageCapacityReservationGiB: '-1'
  StorageCapacityQuotaGiB: '-1'
  UserAndGroupQuotas: '[{"Type": "USER", "Id": 1, "StorageCapacityQuotaGiB": 10}]'
  Tags: '[{"Key": "OPENZFS", "Value": "OPENZFS"}]'
  OptionsOnDeletion: '["DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"]' #SET ON DELETION
reclaimPolicy: Delete
allowVolumeExpansion: false #Not supported for OpenZFS volumes
mountOptions:
  - nfsvers=4.1
  - rsize=1048576
  - wsize=1048576
  - timeo=600
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      # When dynamically provisioning FSx for OpenZFS volumes, the requested storage value is ignored.
      # Instead, the CSI driver uses the storageCapacityReservation and storageCapacityQuota parameters to
      # configure the storage properties of the volume. These values are defined in the storage class.
      # The value below MUST be explicitly set to 1Gi, otherwise the creation will fail.
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: test-nfs
spec:
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: fsx-pvc
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/lifecycle
            operator: In
            values:
            - normal
  imagePullSecrets:
  - name: coder-registry-pull-token
  containers:
  - name: test-nfs
    image: "nginx"
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    volumeMounts:
      - mountPath: "/mnt"
        name: mypd
    command: ["tail"]
    args: ["-f", "/dev/null"]
```
