### ISSUE TITLE
Clone Operations for fsx csi ddriver

### ISSUE THREAD

**Issue by repudi8or** [kubernetes-sigs/aws-fsx-openzfs-csi-driver#60]
i am trying to create a stateful set, that, on scale up, copies the storage from the first replica using volumeClaimTemplate like this :

```
   volumeClaimTemplates:
    - metadata:
        name: zfstestpvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "fsx-sc"
        resources:
          requests:
            storage: 1Gi
        dataSource:
          name: zfstestpvc-0
          kind: PersistentVolumeClaim
          apiGroup: ""

```
          
I get the response :
> failed to provision volume with StorageClass "fsx-sc": CSI driver does not support clone operations: controller CLONE_VOLUME capability is not reported 
i'm going to have to work around the need with snapshot/restore

/feature

Please add a feature to CSI driver to support clone operations
