### ISSUE TITLE
NFSv3 Mounts fail unless the --nolock mount option is specified

### ISSUE THREAD

**Issue by hughdanliu** [kubernetes-sigs/aws-fsx-openzfs-csi-driver#61]
/kind bug

**What happened?**
I attempted to mount an FSx for OpenZFS file system on an application pod using NFSv3 and received this error:
```
Output: mount.nfs: rpc.statd is not running but is required for remote locking. mount.nfs: Either use '-o nolock' to keep locks local, or start statd. mount.nfs: mounting ___ failed, reason given by server: No such file or directory
```
Even though the rpc-statd service was running on the node.
**What you expected to happen?**
NFSv3 mounts succeed without needing to provide the nolock mount option.

**How to reproduce it (as minimally and precisely as possible)?**
Attempt to mount a file system using NFSv3

**Anything else we need to know?**:
Nope

**Environment**
- Kubernetes version (use `kubectl version`): 1.24
- Driver version: v1.1.0

**Comment by hughdanliu** [comment]
Likely an issue with the node daemonset pod permissions. Things tried:
* Setting hostNetwork: true, hostIPC: true, and hostPID: true on the node daemonset pods
This got us around the rpc.statd missing error, but produced this error:
```
mount.nfs: access denied by server while mounting
```

**Comment by heisenbergye** [comment]
it could work if resourcetype is "volume" , @hughdanliu you can try as follow：

StorageClass
1, manually create filesystem, and find the fsx volumeid(rootpath)
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx-sc
provisioner: fsx.openzfs.csi.aws.com
parameters:
  ResourceType: "volume" #REQUIRED
  ParentVolumeId: '"fsvol-074794c3290beb13c"' #REQUIRED
  CopyTagsToSnapshots: 'false'
  DataCompressionType: '"NONE"'
  NfsExports: '[{"ClientConfigurations": [{"Clients": "*", "Options": ["rw","crossmnt"]}]}]'
  ReadOnly: 'false'
  RecordSizeKiB: '128'
  StorageCapacityReservationGiB: '-1'
  StorageCapacityQuotaGiB: '-1'
  UserAndGroupQuotas: '[{"Type": "USER", "Id": 1, "StorageCapacityQuotaGiB": 10}]'
  Tags: '[{"Key": "OPENZFS", "Value": "OPENZFS"}]'
  OptionsOnDeletion: '["DELETE_CHILD_VOLUMES_AND_SNAPSHOTS"]' #SET ON DELETION
reclaimPolicy: Delete
allowVolumeExpansion: false #Not supported for OpenZFS volumes
mountOptions:
  - noatime
  - nfsvers=3
  - sync
  - nolock
  - nconnect=16
  - rsize=1048576
  - wsize=1048576
  - timeo=600
 ----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      # When dynamically provisioning FSx for OpenZFS volumes, the requested storage value is ignored.
      # Instead, the CSI driver uses the storageCapacityReservation and storageCapacityQuota parameters to
      # configure the storage properties of the volume. These values are defined in the storage class.
      # The value below MUST be explicitly set to 1Gi, otherwise the creation will fail.
      storage: 1Gi   # ignore
```


static PV
1. manually create volume  belogs to the filesystem perior
2. specific VolumePath in PV as volume path
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - nfsvers=3
    - sync
    - nolock
    - nconnect=16
    - rsize=1048576
    - wsize=1048576
    - timeo=600
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: fsx.openzfs.csi.aws.com
    volumeHandle: "fsvol-0c6e8bf9b510e0565" 
    volumeAttributes:
      DNSName: "fs-0c8153dfe2d7cc52f.fsx.us-west-2.amazonaws.com"   #REQUIRED
      VolumePath: "/fsx/vol1"    #REQUIRED
      ResourceType: "volume"  #REQUIRED
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: fsx-pv

```
